on: [push, pull_request]
name: build
jobs:
  unit_test:
    if: (github.repository == 'openshift-online/ocm-client-lib')
    strategy:
      matrix:
        go-version: [1.20.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: make test

  go-linter:
    if: (github.repository == 'openshift-online/ocm-client-lib')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: golangci-lint
      run: make linter
